### ISSUE TITLE
A Member cannot be spawned on macOS or Windows: the executable check accepts only ELF and shebang

### ISSUE THREAD

**Issue by ChristopherKahler** [ChristopherKahler/cadre#25]
Cadre cannot resolve a `claude` binary on macOS or Windows, because the check that decides whether a file is executable accepts only two file formats and neither is the native one on those platforms.

## The line

`src/firm/pulse/spawn.py:171`

```python
return head[:4] == b"\x7fELF" or head[:2] == b"#!"
```

`_is_execable` reads the first four bytes and returns true only for an ELF image or a shebang. ELF is the Linux executable format. A native binary on macOS is Mach-O (`cffaedfe` for 64-bit little-endian, `cafebabe` for a universal binary) and on Windows is PE (`MZ`). None of those match, so `_is_execable` returns false for every real native binary on those two platforms.

The docstring explains the intent correctly: reject a shim with the execute bit that the kernel would refuse with ENOEXEC. The implementation encodes that intent as "must be Linux".

## What it costs

`resolve_claude_bin` (`src/firm/pulse/spawn.py:174`) uses `_is_execable` on all three of its resolution paths: the explicit `CADRE_CLAUDE_BIN`, every `claude` on PATH, and the native install at `~/.local/bin/claude`. On macOS and Windows all three reject a working binary, and the caller gets `runtime-not-wired`. **A member cannot be spawned on macOS or Windows at all.**

Today that costs nothing in practice, because the framework is developed and run on Linux under WSL. It costs everything the moment anyone installs from a wheel on a Mac, which is the same audience `pip install` is being prepared for in #3 and #18.

## Measured

Workflow run 27 on `fix/mcp-upper-bound` (6e1e227), job `test (macos-latest)`. The workflow sets `CADRE_CLAUDE_BIN: /bin/echo`. On macOS `/bin/echo` is a Mach-O binary, so the check rejects it and the job reports:

```
{"ok": false, "reason": "runtime-not-wired", "detail": "CADRE_CLAUDE_BIN=/bin/echo has the execute bit but is neither an ELF binary nor a script with a shebang -- exec would fail with ENOEXEC"}
```

Six tests fail as a result, and all six trace to that one return:

```
FAILED tests/test_cli_pulse.py::TestRunPulseCli::test_normal_run                        assert 1 == 0
FAILED tests/test_pulse_spawn.py::TestSpawnCommand::test_default_cwd_is_none            'NoneType' object has no attribute 'kwargs'
FAILED tests/test_pulse_spawn.py::TestSpawnPidTracking::test_pid_tracked_during_run     IndexError: list index out of range
FAILED tests/test_pulse_spawn.py::TestSpawnProcessErrors::test_file_not_found           spawn aborted before exec
FAILED tests/test_pulse_spawn.py::TestSpawnProcessErrors::test_os_error                 spawn aborted before exec
FAILED tests/test_pulse_spawn.py::TestSpawnTimeout::test_timeout_returns_timed_out_result  assert False is True
```

The three `Popen`-mocking failures are the tell: the mock is never called, because the abort happens before exec is reached.

The same six fail on `main` at c273cb0 (run 25). This is not caused by #20 or #21; it predates both. `test (ubuntu-latest)` passes on 6e1e227.

## Fix

Accept the executable formats of the platforms Cadre claims to support: ELF, Mach-O 64-bit and universal, PE, and a shebang. The docstring's intent survives intact, since a shell stub with no shebang still fails all four magic checks.

The test suite should not depend on the resolver accepting `/bin/echo`, which is a different format on each runner. A fixture that writes a file with a shebang is portable everywhere.

## Scope note

Filed as a defect, not scheduled. It does not block #20 or #21, and both merge with this red on macOS.
